// <auto-generated />
using AppClientesMexaba.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppClientesMexaba.Migrations
{
    [DbContext(typeof(ClContext))]
    partial class ClContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppClientesMexaba.Models.tcausr", b =>
                {
                    b.Property<string>("cia_ventas")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("cia_ventas")
                        .IsFixedLength();

                    b.Property<string>("nom_cto")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("nom_cto")
                        .IsFixedLength();

                    b.Property<string>("nombre")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("nombre")
                        .IsFixedLength();

                    b.Property<string>("nombre_lar")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("char(40)")
                        .HasColumnName("nombre_lar")
                        .IsFixedLength();

                    b.Property<string>("puesto")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("puesto")
                        .IsFixedLength();

                    b.Property<string>("pwd")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("pwd")
                        .IsFixedLength();

                    b.ToTable((string)null);

                    b.ToView("tcausr", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
